### ISSUE TITLE
Stop Watch Seconds/Reset

### ISSUE THREAD

**Issue by interstaller555** [RobTillaart/Stopwatch_RT#12]
Hello - your code examples don't include how to stop, start, or reset the stop watch. Can you please elaborate on this? It also doesn't elaborate on how to "count up" but 1 minute every time the seconds hit 60, they only keep rolling 61, 62, 63 etc.

**Comment by RobTillaart** [comment]
Thanks for the issue, 
will have a look into it tomorrow.

**Comment by RobTillaart** [comment]
Added an example **stopwatch_demo.ino**
this shows 
- how to use IO pins to control the stopwatch. start stop and reset
- how to indicate with a LED (pin 13 Arduino UNO) that the stopwatch is running.
- how to update a display (serial) every 100 milliseconds
- how to stop updating the display if the stopwatch is not running. (as the time stays the same)

----

How to convert seconds to a string that uses "mm:ss" template is outside the scope of the stopwatch library.
However here a function that does the job, it may not the best way to do it, but should get you started.

```cpp
char * convertMinutes(uint32_t seconds)
{
  static char buf[10];
  uint8_t tmp;

  //  STRIP OFF THE MINUTES
  tmp = seconds / 600;
  seconds = seconds - tmp * 600;
  buf[0] = tmp + '0';
  tmp = seconds / 60;
  seconds = seconds - tmp * 60;
  buf[1] = tmp + '0';
  buf[2] = ':';

  //  DO THE SECONDS
  tmp = seconds / 10;
  seconds = seconds - tmp * 10;
  buf[3] = tmp + '0';
  buf[4] = seconds + '0';
  buf[5] = '\0';
  
return buf;
}

//  example call
Serial.println(convertMinutes(123));
```

**Comment by RobTillaart** [comment]
If this solves the problem, please close the issue.
