### ISSUE TITLE
Unable to compile sample with ESP8622 board, will compile as Arduino Uno

### ISSUE THREAD

**Issue by TrickyRick** [RobTillaart/Stopwatch_RT#3]
I can load and compile the Sample example using a Arduino Uno board.  When I change the board to Node MCU 1.0 (ESP-12E Module) I receive "Error compiling for board NodeMCU 1.0 (ESP-12E Module).  
Error message also includes "StopWatch.cpp:36:14: error: invalid conversion from 'long unsigned int (*)()' to 'uint32_t (*)() {aka unsigned int (*)()}' [-fpermissive]
     _gettime = micros;"

**Comment by RobTillaart** [comment]
The type of micros() and millis have a different signature. I recently came across a similar problem in other code. 
Will work on a solution this week.
Thanks for mentioning it

**Comment by RobTillaart** [comment]
0.2.2 version released, 
verified with ESP32 which gave the same error.

**Comment by TrickyRick** [comment]
Thank you for the quick response.   Loads perfectly now!

**Comment by RobTillaart** [comment]
You're welcome, 
if you find other bugs in my libraries or missing features just let me know and I'll try to fix asap

**Comment by TrickyRick** [comment]
Rob, thanks again for your help.

 

The project I was trying to build is https://github.com/BrianInGermany/ToastmastersTimerWiFi.  I was getting errors and posted an Issue, but BrianInGermany doesn’t seem to be monitoring his project.  I found his documentation slim, and wasn’t even sure if it was your StopWatch.  Now that your part is working ok, I am still getting errors compiling the ToastmastersTimer.ino with similar errors “'class StopWatch' has no member named 'ms'” .

 

I’m more of a hardware guy, but get lost quick in C+.

 

Do you have any advice?

 

Thanks, 

Rick

**Comment by RobTillaart** [comment]
I will check that code if I understand the problem and if it id fixable (time boxed)

**Comment by RobTillaart** [comment]
Quick code scan
The project is based upon an older version of the stopwatch library. 

You must rtry to eplace the calls to .ms() with calls to .elapsed(). That function is renamed after the stopwatch also supported micros and seconds as tome units.

No computer nearby to test myself.

**Comment by TrickyRick** [comment]
Thanks again.  It worked!

 

Rick
